export const Type = {
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_ALL_VENDORS: 'GET_ALL_VENDORS',
  GET_ALL_PLACES: 'GET_ALL_PLACES',
  GET_TOTAL_VENDORS: 'GET_TOTAL_VENDORS',

  SET_COUNTRIES: 'SET_COUNTRIES'
}
