export const Type = {
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  GET_ALL_VENDORS: 'GET_ALL_VENDORS',
  GET_ALL_PLACES: 'GET_ALL_PLACES',
  GET_ALL_BUSINESS_BY_FILTER: 'GET_ALL_BUSINESS_BY_FILTER',
  GET_TOTAL_VENDORS: 'GET_TOTAL_VENDORS',
  GET_BUSINESS: 'GET_BUSINESS',
  GET_ALL_INQUERIES: 'GET_ALL_INQUERIES',

  SAVE_BUSINESS_FOR_OFFER: 'SAVE_BUSINESS_FOR_OFFER',

  SET_COUNTRIES: 'SET_COUNTRIES',
  SET_ZONE1: 'SET_ZONE1'
}
